name: CI/CD with CMake

on:
  push:
    branches:
      - main  # Change to your default branch

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up CMake
      uses: actions/setup-cmake@v1
      with:
        cmake-version: '3.20'  # Change to your required version
        
    - name: Configure CMake
      run: cmake -S . -B build
      
    - name: Build
      run: cmake --build build
      
    - name: Run tests
      run: cd build && ctest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        # Add your deployment script or commands here

